### ISSUE TITLE
Add a list of the studies that were "touched" by each job

### ISSUE THREAD

**Issue by antgonza** [qiita-spots/qp-knight-lab-processing#15]
We decided that it would be beneficial to create a "list" of studies that the "sequencing processing job" created files to so admins can quickly go to them; an option is to show it in the job status when "success".

**Comment by charles-cowart** [comment]
Tentatively resolved w/ https://github.com/qiita-spots/qp-knight-lab-processing/pull/22

Any Qiita study that has one or more output files from qp-klp moved into its upload directory will become an entry in a new output file named 'touched_studies.tsv'. The TSV file will contain the study_id, the project it's associated with, and URLs to the detailed study pages in both qiita-rc.ucsd.edu and qiita.ucsd.edu.

**Comment by charles-cowart** [comment]
Resolved with:
https://github.com/qiita-spots/qp-knight-lab-processing/pull/22
https://github.com/qiita-spots/qp-knight-lab-processing/pull/25
