### ISSUE TITLE
some blanks have the wrong char separator

### ISSUE THREAD

**Issue by antgonza** [qiita-spots/qp-knight-lab-processing#17]
for whatever reason some times blanks with name like BLANKHA_2B are written like that vs the correct form BLANKHA.2B

**Comment by charles-cowart** [comment]
We may need more detail. After reviewing the cache of sample-sheets I have on-hand, I've noticed that most of the time, the sample-id and/or sample-name are written with an '_', while the well-description might be '.'. My thinking is if we want to change that behavior we either need to make it an error and have the user fix it, or automatically perform the replacement in the sample-sheet ourselves.

**Comment by antgonza** [comment]
Got it - for whatever reason I thought we actually had some kind of parser/search-replace thing already in place; however, it sounds like we are currently just ignoring the '_'. I think automatic fixing will be the best because if we ask the user to fix at this stage it might create more problems and could be avoided by auto-fixing. 

Now, this might be an issue with duplicated names, for example: BLANKHA_2B vs BLANKHA.2B so perhaps better to add a check in the metapool notebook; what do you think?

**Comment by charles-cowart** [comment]
I think it might be good to put it in mg-script's extended validation for now. These kinds of strings we see in several columns 'Sample_ID', 'Sample_Name', 'Well_description' to name a few. I've also noticed a few instances of strings having '..' instead of '.'. Putting it in mg-scripts gives us a lot of leeway to tailor the sanitizing to our specific needs.

**Comment by charles-cowart** [comment]
After discussions with @antgonza  and wet-lab, sample_ids will continue to have '_' as is required by bcl-convert. sample_names will have '.' as required by Qiita.
