### ISSUE TITLE
The call to bcl-convert does not place filenames within quotes

### ISSUE THREAD

**Issue by wasade** [qiita-spots/qp-knight-lab-processing#19]
This was observed when a sample sheet with spaces in the filename was accidentally used.

**Comment by charles-cowart** [comment]
Tentatively resolving this by sanitizing the filename supplied to the plugin before the sample-sheet is written out to disk.

**Comment by charles-cowart** [comment]
Resolved w/
[the following line](https://github.com/biocore/mg-scripts/blob/a83fc65faa83f839264688693952f27bfb69b4b3/sequence_processing_pipeline/ConvertJob.py#L105)
