### ISSUE TITLE
Enable access to all sequencer output locations

### ISSUE THREAD

**Issue by adswafford** [qiita-spots/qp-knight-lab-processing#2]
In the current webpage for kicking off the bcl to fastq pipeline, only the runid is specified, with the parent directories being the igm ftp mirror (/sequencing/igm_runs/) and possibly also the location where the MiSeq in the KL is writing to. However the MiniSeq output location /sequencing/cmi_sequencing/ needs to be added (and the MiSeq output location if it's not already included).

If in the future due to down instruments, instrument availability, etc. the KL, CMI, or a collaborating lab runs a sample elsewhere, e.g. LJI, Salk, TSRI, or a more far flung sequencing center, we'll have to clone all the data over to one of these locations on barnacle instead of simply processing it from there, so it may make sense to either:
1) add a box where the parent directory location can be specified
or
2) have a separate admin function to scp data from another location to a location on barnacle

**Comment by antgonza** [comment]
This has already been solved via the configuration file.
