### ISSUE TITLE
The Knight Lab iSeq needs to be described in INSTRUMENT_LOOKUP

### ISSUE THREAD

**Issue by wasade** [qiita-spots/qp-knight-lab-processing#20]
...currently it is not present.

**Comment by antgonza** [comment]
... what's the name? "The Knight Lab iSeq"?

**Comment by wasade** [comment]
Not sure :)

**Comment by wasade** [comment]
One important item is that the instrument prefix is pulled, which for iSeq is "FS" which is currently not represented in the `INSTRUMENT_LOOKUP`

**Comment by wasade** [comment]
Fixed in biocore/metagenomics_pooling_notebook#65
