### ISSUE TITLE
Hardcoded information in amplicon processing

### ISSUE THREAD

**Issue by wasade** [qiita-spots/qp-knight-lab-processing#50]
It's unclear why there is a hard coded sequencing run and other details in the amplicon processing, see https://github.com/qiita-spots/qp-knight-lab-processing/blob/8696401a3aa4bdce6135b5a66e6186af8da603b8/qp_klp/process_amplicon_job.py#L329-L355

**Comment by charles-cowart** [comment]
This was part of a kludge written to support unittests when running locally or under CI, as opposed to production.

This was removed when the qp-klp was refactored in late-spring/early summer '23.
