### ISSUE TITLE
Unusual error from amplicon processing

### ISSUE THREAD

**Issue by wasade** [qiita-spots/qp-knight-lab-processing#52]
This refers to job 177b4a96-abde-4180-819a-026098f98691. It appears to be referencing a file in uploads that does not exist.

I attempted to recreate this issue in job 15d22063-7b43-4e66-b69c-d51f7b5575b1, however that job reports as successful. Unfortunately, I accidentally used a slightly different sample sheet, however the sheet is qualitatively the same as the one in the erroneous job as it corresponds to replicates.

**Comment by charles-cowart** [comment]
@antgonza @wasade I think it's okay to close this one. We've had changes to the code since then, this job is likely no longer available, and the issue has not appeared since then.

**Comment by antgonza** [comment]
I agree that is fine to close as the issue was that the user tried to use the error from another job as the input run_identifier.
